export const dogSpecificStatusType = {
  PREGNANT: 'PREGNANT',
  LACTATING: 'LACTATING',
  // PREGNANT_EARLY: 'PREGNANT_EARLY',
  // PREGNANT_LATE: 'PREGNANT_LATE',
  LACTATING_ONE_TO_TWO: 'LACTATING_ONE_TO_TWO',
  LACTATING_THREE_TO_FOUR: 'LACTATING_THREE_TO_FOUR',
  LACTATING_FIVE_TO_SIX: 'LACTATING_FIVE_TO_SIX',
  LACTATING_OVER_SEVEN: 'LACTATING_OVER_SEVEN',
  KOR: {
    PREGNANT: '임신한 상태예요',
    LACTATING: '수유 중이에요',
    LACTATING_ONE_TO_TWO: '1~2마리',
    LACTATING_THREE_TO_FOUR: '3~4마리',
    LACTATING_FIVE_TO_SIX: '5~6마리',
    LACTATING_OVER_SEVEN: '7마리 이상',
  },
};
